# Generated by Django 5.0.3 on 2024-05-23 07:29

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ptikstory",
            name="gallery",
        ),
        migrations.RemoveField(
            model_name="ptikstory",
            name="video",
        ),
        migrations.AlterField(
            model_name="faculty",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Description"
            ),
        ),
    ]
