# Generated by Django 5.0.3 on 2024-05-23 07:35

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0002_remove_ptikstory_gallery_remove_ptikstory_video_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationSubjectsCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Education Subject Category",
                "verbose_name_plural": "Education Subject Categories",
                "db_table": "education_subjects_category",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="EducationSubjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Full Name"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Phone"
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "problem",
                    models.TextField(blank=True, null=True, verbose_name="Problem"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "short_title",
                    models.CharField(max_length=255, verbose_name="Short Title"),
                ),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Short Description"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="education_subjects/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="education_subjects/",
                        verbose_name="Video",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="university.educationsubjectscategory",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Education Subject",
                "verbose_name_plural": "Education Subjects",
                "db_table": "education_subjects",
                "ordering": ["id"],
            },
        ),
    ]
