# Generated by Django 5.0.3 on 2024-05-23 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0002_file"),
    ]

    operations = [
        migrations.DeleteModel(
            name="File",
        ),
        migrations.DeleteModel(
            name="Gallery",
        ),
        migrations.DeleteModel(
            name="Video",
        ),
    ]
