# Generated by Django 5.0.3 on 2024-05-22 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_customuser_options_alter_customuser_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="customuser",
            table="users",
        ),
    ]
